-- MySQL Script generated by MySQL Workbench
-- Thu Oct  4 18:08:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_monedas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_monedas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_monedas` DEFAULT CHARACTER SET utf8 ;
USE `sistema_monedas` ;

-- -----------------------------------------------------
-- Table `sistema_monedas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_persona` VARCHAR(50) NULL,
  `nombre_usuario` VARCHAR(50) NULL,
  `dni_usuario` VARCHAR(50) NULL,
  `email_usuario` VARCHAR(100) NULL,
  `tipo_usuario` INT NULL,
  `membresia` INT NULL,
  `membresia_comienzo` DATETIME NULL,
  `membresia_fin` DATETIME NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `dni_usuario_UNIQUE` (`dni_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_usuario_UNIQUE` (`email_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`catalogo_monedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`catalogo_monedas` (
  `id_catalogo_moneda` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL,
  PRIMARY KEY (`id_catalogo_moneda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`coleccion_personal_monedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`coleccion_personal_monedas` (
  `id_coleccion_personal_moneda` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `id_moneda` INT NULL,
  `condicion_moneda` VARCHAR(45) NULL,
  `casa_certificadora` VARCHAR(45) NULL,
  `valor_certificacion` VARCHAR(45) NULL,
  `registro_certificacion` VARCHAR(80) NULL,
  `tipo_registro` VARCHAR(50) NULL,
  `precio_moneda` VARCHAR(45) NULL,
  `mercado` VARCHAR(45) NULL,
  `precio_referencia` VARCHAR(45) NULL,
  `lugar_moneda` VARCHAR(100) NULL,
  `cantidad_moneda` VARCHAR(45) NULL,
  PRIMARY KEY (`id_coleccion_personal_moneda`),
  INDEX `fk_coleccion_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_coleccion_catalogo_idx` (`id_moneda` ASC) VISIBLE,
  CONSTRAINT `fk_coleccionm_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_monedas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleccionm_catalogo`
    FOREIGN KEY (`id_moneda`)
    REFERENCES `sistema_monedas`.`catalogo_monedas` (`id_catalogo_moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`catalogo_billetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`catalogo_billetes` (
  `id_catalogo_billete` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL,
  PRIMARY KEY (`id_catalogo_billete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`coleccion_personal_billetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`coleccion_personal_billetes` (
  `id_coleccion_personal_billete` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `id_billete` INT NULL,
  `condicion_billete` VARCHAR(45) NULL,
  `casa_certificadora` VARCHAR(45) NULL,
  `valor_certificacion` VARCHAR(45) NULL,
  `registro_certificacion` VARCHAR(80) NULL,
  `tipo_registro` VARCHAR(50) NULL,
  `precio_billete` VARCHAR(45) NULL,
  `mercado` VARCHAR(45) NULL,
  `serie_billete` VARCHAR(45) NULL,
  `precio_referencia` VARCHAR(45) NULL,
  `lugar_billete` VARCHAR(100) NULL,
  `cantidad_billete` VARCHAR(45) NULL,
  PRIMARY KEY (`id_coleccion_personal_billete`),
  INDEX `fk_coleccionb_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_coleccionb_catalogo_idx` (`id_billete` ASC) VISIBLE,
  CONSTRAINT `fk_coleccionb_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_monedas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleccionb_catalogo`
    FOREIGN KEY (`id_billete`)
    REFERENCES `sistema_monedas`.`catalogo_billetes` (`id_catalogo_billete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`sugerencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`sugerencias` (
  `id_sugerencia` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `descripcion` LONGTEXT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_sugerencia`),
  INDEX `fk_sugerencia_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_sugerencia_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_monedas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`atributos_m`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`atributos_m` (
  `id_atributo_m` INT NOT NULL AUTO_INCREMENT,
  `nombre_atributo` VARCHAR(100) NULL,
  `descripcion_atributo` VARCHAR(100) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_atributo_m`),
  UNIQUE INDEX `nombre_atributo_UNIQUE` (`nombre_atributo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`atributo_monedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`atributo_monedas` (
  `id_atributo_moneda` INT NOT NULL AUTO_INCREMENT,
  `id_moneda` INT NULL,
  `id_atributo` INT NULL,
  `atributo_moneda` VARCHAR(100) NULL,
  PRIMARY KEY (`id_atributo_moneda`),
  INDEX `fk_atributo_catalogo_idx` (`id_moneda` ASC) VISIBLE,
  INDEX `fk_atributo_attr_idx` (`id_atributo` ASC) VISIBLE,
  CONSTRAINT `fk_atributo_catalogom`
    FOREIGN KEY (`id_moneda`)
    REFERENCES `sistema_monedas`.`catalogo_monedas` (`id_catalogo_moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributo_attrm`
    FOREIGN KEY (`id_atributo`)
    REFERENCES `sistema_monedas`.`atributos_m` (`id_atributo_m`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`atributos_b`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`atributos_b` (
  `id_atributo_b` INT NOT NULL AUTO_INCREMENT,
  `nombre_atributo` VARCHAR(100) NULL,
  `descripcion_atributo` VARCHAR(100) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_atributo_b`),
  UNIQUE INDEX `nombre_atributo_UNIQUE` (`nombre_atributo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_monedas`.`atributo_billetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_monedas`.`atributo_billetes` (
  `id_atributo_billete` INT NOT NULL AUTO_INCREMENT,
  `id_billete` INT NULL,
  `id_atributo` INT NULL,
  `atributo_billete` VARCHAR(100) NULL,
  PRIMARY KEY (`id_atributo_billete`),
  INDEX `fk_atributo_catalogo_idx` (`id_billete` ASC) VISIBLE,
  INDEX `fk_atributo_attrb_idx` (`id_atributo` ASC) VISIBLE,
  CONSTRAINT `fk_atributo_catalogob`
    FOREIGN KEY (`id_billete`)
    REFERENCES `sistema_monedas`.`catalogo_billetes` (`id_catalogo_billete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributo_attrb`
    FOREIGN KEY (`id_atributo`)
    REFERENCES `sistema_monedas`.`atributos_b` (`id_atributo_b`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
